# ============================================================
# ARC-NEXUS - VISION ENGINE
# File: app/vision.py
# Version: 007 (Dual-artifact: raw_content=ocr_text, brief=image analysis)
#
# IMAGE COLLECT PIPELINE
# ─────────────────────────────────────────────────────────────
# 1. Tesseract OCR  — always attempted in local mode.
#    Returns text or a clear "[OCR UNAVAILABLE]" / "[OCR ERROR]"
#    message if Tesseract is missing or fails.
#
# 2. Ollama vision  — attempted only when the configured model
#    (NEXIS_VISION_MODEL) is found in `ollama list`.
#    If the model is absent or Ollama is offline, a clear
#    "unavailable" note replaces the description.
#
# 3. Separate storage — OCR text stored as raw_content (used by Convert/Create),
#    visual description stored as brief (AI analysis layer).
#
# Hosted mode: all image analysis blocked (503).
# ============================================================

import asyncio

from fastapi import APIRouter, UploadFile, File, HTTPException, Depends
from sqlalchemy.orm import Session
from app.core.db import get_db
from app.core import usage as usage_tracker
from app.core.usage import DEFAULT_USER_ID


# ------------------------------------------------------------
# Router
# ------------------------------------------------------------
router = APIRouter(tags=["nexis-vision"])


# ------------------------------------------------------------
# IMAGE BRIEF BUILDER
# Builds the AI analysis section only.
# Raw OCR text is stored separately as raw_content.
# ------------------------------------------------------------
def _build_image_brief(
    filename: str,
    visual_description: str | None,
    vision_model: str | None,
) -> str:
    sep = "═" * 48

    lines = [
        "IMAGE COLLECTION BRIEF",
        sep,
        f"File: {filename}",
        "",
    ]

    # ── Visual Description ───────────────────────────────────
    lines.append("Visual Description:")
    if visual_description:
        lines.append(visual_description)
    else:
        lines.append(
            "Visual description unavailable — no local vision model configured.\n"
            "To enable: install a vision-capable model in Ollama and set\n"
            "NEXIS_VISION_MODEL=<model-name> in your .env file."
        )

    lines.append("")

    # ── Notes ────────────────────────────────────────────────
    lines.append("Notes:")
    lines.append("- OCR may contain errors. Results depend on image quality and text clarity.")
    if vision_model:
        lines.append(f"- Visual description generated by {vision_model} via local Ollama.")
    else:
        lines.append("- Visual description skipped: no vision model available or configured.")
    lines.append("- Raw OCR text is preserved separately in this collection item.")

    return "\n".join(lines)


# ------------------------------------------------------------
# POST /vision/analyze
# Multimodal image collect: OCR + visual description
# ------------------------------------------------------------
@router.post("/analyze")
async def analyze_image(file: UploadFile = File(...), db: Session = Depends(get_db)):

    from app.core.config import settings

    # ── Validate file ─────────────────────────────────────────
    if not file:
        raise HTTPException(status_code=400, detail="No file uploaded.")

    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File must be an image.")

    # ── Usage limit check ─────────────────────────────────────
    limit_error = usage_tracker.check_raw_input_limits(db, DEFAULT_USER_ID)
    if limit_error:
        raise HTTPException(status_code=429, detail=limit_error)

    # ── Read bytes ────────────────────────────────────────────
    try:
        image_bytes = await file.read()
    except Exception:
        raise HTTPException(status_code=400, detail="Failed to read uploaded file.")

    if not image_bytes:
        raise HTTPException(status_code=400, detail="Empty image file.")

    original_filename = file.filename or "image"

    # ── Hosted mode: block all image analysis ─────────────────
    if settings.NEXIS_HOSTED_MODE:
        raise HTTPException(
            status_code=503,
            detail="Image analysis is not available in hosted beta mode.",
        )

    # ── Step 1: OCR (Tesseract, always attempted) ─────────────
    from ingestion.ocr_utils import extract_text_from_image
    ocr_task = extract_text_from_image(image_bytes)

    # ── Step 2: Vision availability probe ────────────────────
    # Check Ollama synchronously (fast /api/tags probe, ~200 ms).
    # Done before firing the generate call to give a clean
    # "not configured" message rather than a connection error.
    vision_model = settings.NEXIS_VISION_MODEL.strip()
    ollama_url = settings.OLLAMA_URL.rstrip("/")

    from app.services.vision_service import (
        check_vision_model_available,
        describe_for_collection,
        run_llava,
    )

    model_available = await asyncio.get_event_loop().run_in_executor(
        None, check_vision_model_available, vision_model, ollama_url
    )

    # ── Step 3: Run OCR + vision concurrently ─────────────────
    if model_available:
        ocr_text, visual_description = await asyncio.gather(
            ocr_task,
            describe_for_collection(image_bytes),
        )
    else:
        ocr_text = await ocr_task
        visual_description = None

    # ── Step 4: Build image brief (AI analysis only) ─────────────
    brief = _build_image_brief(
        filename=original_filename,
        visual_description=visual_description,
        vision_model=vision_model if model_available else None,
    )

    # ── Commit usage ──────────────────────────────────────────
    usage_tracker.increment_raw_input(db, DEFAULT_USER_ID)

    # ── Return structured response ────────────────────────────
    return {
        "type": "image",
        "description": brief,              # backward compat (set to brief for display)
        "raw_content": ocr_text,           # pure OCR text for Convert/Create
        "brief": brief,                    # AI analysis (visual description + notes)
        "ocr_text": ocr_text,              # same as raw_content
        "visual_description": visual_description or "",
        "thumbnail": None,
    }